---
name: 🧪 Testing
run-name: ${{ github.workflow }} - ${{ toJson(inputs) }}
concurrency: {group: "${{ github.workflow }}"}
env: {TZ: Asia/Shanghai}

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: Runner, default to `"ubuntu-slim"`
        required: false
        type: string
        default: '"ubuntu-slim"'

jobs:
  debug:
    runs-on: ${{ fromJson(inputs.runs-on||'ubuntu-slim') }}
    timeout-minutes: 5
    defaults: {run: {shell: bash}}

    # `id-token` is required for fetching OIDC token
    permissions: {id-token: write, contents: read}

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v7
        with: {persist-credentials: false}

      - name: 🔑 Generate Huawei Cloud temporary credentials
        id: creds
        uses: ./
        with:
          provider-urn: iam::019e8bf561d17480b97b8215caafc3a1:oidcProvider:github_com
          agency-urn: iam::019e8bf561d17480b97b8215caafc3a1:agency:gh-oidc-tes

      - name: 🔍 Print outputs of previous step
        env: {STEP_OUTPUTS: "${{ toJson(steps.creds.outputs) }}"}
        run: jq -C <<<"$STEP_OUTPUTS"

      - name: 🖥️ Setup Huawei Cloud KooCLI for testing
        uses: vbem/setup-hcloud@main

      - name: 🧪 Test temporary credentials using KooCLI
        run: |-
          hcloud sts GetCallerIdentity --cli-region=cn-east-3 \
            --cli-access-key="${HUAWEICLOUD_SDK_AK}" \
            --cli-secret-key="${HUAWEICLOUD_SDK_SK}" \
            --cli-security-token="${HUAWEICLOUD_SDK_SECURITY_TOKEN}" \
            | jq -C
